game = {'grid_size': (192, 128), 'num_tiles': (6, 4), 'tile_size': 32, 'animate_ct': 6, 'game_fps': 18,
        'dirt_spots': [1, 2, 3, 4, 5, 11, 17, 19, 20, 21, 22, 23],
        'special': {0: 0, 6: 1, 7: 2, 12: 3, 13: 4, 18: 5},
        'numberX_locations_top': [21, 54, 84, 115, 148, 180], 'numberY_location_top': 1,
        'numberX_locations_bottom': [19, 52, 85, 115, 150, 182], 'numberY_location_bottom': 122,
        'overlay1_resources': [6, 7, 8, 9, 10, 11], 'overlay2_resources': [0, 1, 2, 3, 4, 5]}

penguin = {'start_x': 85, 'start_y': 55, 'center_px_x_offset': 9, 'center_px_y_offset': 10, 'num_sprites': 4}

resources = ['0wheat', '1silk', '2metal', '3sand', '4oil', '5plastic', '6shiners', '7blennies', '8guppies',
             '9angels', '10jellies', '11trophies']

construct_menu = {'offset_x': 108, 'offset1': 64, 'offset2': 71, 'offset3': 78, 'offset4': 85,
                  'resources': [2, 4, 9, 10]}

factories = {
    'wheat_farm': dict(name='wheat_farm', bldg_num=1,
                       build_cost1=100, build_cost2=100, build_cost3=100, build_cost4=100,
                       num_on_sprites=1, num_off_sprites=1, animation_rate=2,
                       x_coord=36, y_coord=5, grid_pos=1,
                       fuel1_type=12, fuel2_type=1, fuel1_ipo=2, fuel2_ipo=30,
                       numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                       product=0, special=False,
                       upgrade_mult=1.05, upgrade_cost1=10, upgrade_cost2=10, upgrade_type1=3, upgrade_type2=4,
                       ops_per_tick_add=0.2,
                       build_next=['cereal_factory', 'mine', 'silk_farm']
                       ),
    'silk_farm': dict(name='silk_farm', bldg_num=2,
                      build_cost1=100, build_cost2=100, build_cost3=100, build_cost4=100,
                      num_on_sprites=1, num_off_sprites=1, animation_rate=2,
                      x_coord=36, y_coord=5, grid_pos=2,
                      fuel1_type=12, fuel2_type=1, fuel1_ipo=2, fuel2_ipo=30,
                      numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                      product=0, special=False,
                      upgrade_mult=1.05, upgrade_cost1=10, upgrade_cost2=10, upgrade_type1=3, upgrade_type2=4,
                      ops_per_tick_add=0.2,
                      build_next=['net_weaver']
                      ),
    'mine': dict(name='mine', bldg_num=3,
                 build_cost1=130, build_cost2=100, build_cost3=13, build_cost4=14,
                 num_on_sprites=1, num_off_sprites=1, animation_rate=2,
                 x_coord=20, y_coord=20, grid_pos=20,
                 fuel1_type=12, fuel2_type=1, fuel1_ipo=30, fuel2_ipo=30,
                 numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                 product=2, special=False,
                 upgrade_mult=1.05,
                 ops_per_tick_add=0.5,
                 build_next=['digger', 'drill']
                 ),
    'digger': dict(name='digger', bldg_num=4,
                   build_cost1=130, build_cost2=100, build_cost3=13, build_cost4=14,
                   num_on_sprites=1, num_off_sprites=1, animation_rate=2,
                   x_coord=20, y_coord=20, grid_pos=19,
                   fuel1_type=12, fuel2_type=1, fuel1_ipo=30, fuel2_ipo=30,
                   numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                   product=3, special=False,
                   upgrade_mult=1.05,
                   ops_per_tick_add=0.5,
                   build_next=['glassblower']
                   ),
    'drill': dict(name='drill', bldg_num=5,
                  build_cost1=130, build_cost2=100, build_cost3=13, build_cost4=14,
                  num_on_sprites=1, num_off_sprites=1, animation_rate=2,
                  x_coord=20, y_coord=20, grid_pos=21,
                  fuel1_type=12, fuel2_type=1, fuel1_ipo=30, fuel2_ipo=30,
                  numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                  product=4, special=False,
                  upgrade_mult=1.05,
                  ops_per_tick_add=0.5,
                  build_next=['plastic_plant']
                  ),
    'cereal_factory': dict(name='cereal_factory', bldg_num=6,
                           build_cost1=100, build_cost2=100, build_cost3=0, build_cost4=0,
                           num_on_sprites=4, num_off_sprites=1, animation_rate=2,
                           x_coord=2, y_coord=34, grid_pos=22,
                           fuel1_type=0, fuel2_type=1, fuel1_ipo=30, fuel2_ipo=30,
                           numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                           product=7, special=True,
                           upgrade_mult=1.05, upgrade_cost1=10, upgrade_cost2=10, upgrade_type1=3, upgrade_type2=4,
                           ops_per_tick_add=0.5,
                           build_next=[]
                           ),
    'net_weaver': dict(name='net_weaver', bldg_num=7,
                       build_cost1=100, build_cost2=100, build_cost3=0, build_cost4=100,
                       num_on_sprites=1, num_off_sprites=1, animation_rate=2,
                       x_coord=20, y_coord=20, grid_pos=4,
                       fuel1_type=2, fuel2_type=1, fuel1_ipo=30, fuel2_ipo=30,
                       numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                       product=5, special=True,
                       upgrade_mult=1.05,
                       ops_per_tick_add=0.4,
                       build_next=[]
                       ),
    'plastic_plant': dict(name='plastic_plant', bldg_num=8,
                          build_cost1=100, build_cost2=100, build_cost3=0, build_cost4=0,
                          num_on_sprites=4, num_off_sprites=1, animation_rate=2,
                          x_coord=2, y_coord=34, grid_pos=3,
                          fuel1_type=0, fuel2_type=1, fuel1_ipo=30, fuel2_ipo=30,
                          numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                          product=7, special=False,
                          upgrade_mult=1.05, upgrade_cost1=10, upgrade_cost2=10, upgrade_type1=3, upgrade_type2=4,
                          ops_per_tick_add=0.5,
                          build_next=['line_maker', 'lure_maker']
                          ),
    'line_maker': dict(name='line_maker', bldg_num=9,
                       build_cost1=100, build_cost2=100, build_cost3=0, build_cost4=100,
                       num_on_sprites=1, num_off_sprites=1, animation_rate=2,
                       x_coord=20, y_coord=20, grid_pos=11,
                       fuel1_type=2, fuel2_type=1, fuel1_ipo=30, fuel2_ipo=30,
                       numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                       product=5, special=True,
                       upgrade_mult=1.05,
                       ops_per_tick_add=0.4,
                       build_next=[]
                       ),
    'lure_maker': dict(name='lure_maker', bldg_num=10,
                       build_cost1=130, build_cost2=100, build_cost3=12, build_cost4=1,
                       num_on_sprites=1, num_off_sprites=1, animation_rate=2,
                       x_coord=20, y_coord=20, grid_pos=17,
                       fuel1_type=12, fuel2_type=10, fuel1_ipo=30, fuel2_ipo=30,
                       numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                       product=9, special=True,
                       upgrade_mult=1.05,
                       ops_per_tick_add=0.5,
                       build_next=[]
                       ),
    'glassblower': dict(name='glassblower', bldg_num=11,
                        build_cost1=130, build_cost2=100, build_cost3=10, build_cost4=1,
                        num_on_sprites=1, num_off_sprites=1, animation_rate=2,
                        x_coord=20, y_coord=20, grid_pos=5,
                        fuel1_type=1, fuel2_type=1, fuel1_ipo=30, fuel2_ipo=30,
                        numY_offset=18, num1_offset=13, num2_offset=17, num3_offset=21,
                        product=-1, special=True,
                        upgrade_mult=1.05,
                        ops_per_tick_add=0.5,
                        build_next=[]
                        ),
}

fishing = dict(
    shiner_chance=30, blenny_chance=30, guppy_chance=30, angel_chance=5, jelly_chance=5,
    num_on_sprites=1, animation_rate=2, catch_rate=2
)
